# Generated by Django 5.2.17 on 2026-08-19 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Applied', max_length=30)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='careers.career')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
